### ISSUE TITLE
Problem on travis.ci

### ISSUE THREAD

**Issue by vddgil** [grantspeelman/cypress-on-rails#4]
Hello,

I have 3 simple tests working well on my local machine.
I try to run the tests on travis.ci, but I have a 500 error as reponse from the middleware for the clean command... The server logs are pretty empty, I only have one line for the POST on /__cypress__/command

I'm stuck, maybe somebody can help me at least to have a little bit more logs

Thanks in advance,

Gil

**Comment by grantspeelman** [comment]
Sorry about the delayed response @vddgil, only see this now, forgot to turn notifications on for this repo.

**Comment by grantspeelman** [comment]
@vddgil let me know if this is still an issue for you.
Also make sure to enable logging in your cypress_dev initializer
EG
```ruby
  CypressDev.configure do |c|
    c.logger = Rails.logger
  end
```
