### ISSUE TITLE
Trigger test run from server 

### ISSUE THREAD

**Issue by blahutka** [grantspeelman/cypress-on-rails#5]
Hello there,
When I change HTML view on my server I would like to tell Cypress to trigger test run. Is there any API that I can use to call and run specific test file?

For example watch server files with Guard and trigger this call.

**Comment by grantspeelman** [comment]
this is a feature the cypress team is still working on and not something this gem will implement

Keep you eye on the following feature: https://github.com/cypress-io/cypress/issues/456

Hope that helps.
